// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: todos.sql

package schema

import (
	"context"
)

const listTodo = `-- name: ListTodo :many
SELECT id, user_id, title, completed, created_at, updated_at FROM todos
`

func (q *Queries) ListTodo(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
